---
# HassCancelTimer - default

language: "tr"
data:
  - sentences:
      - "<zamanlayici_i> <timer_iptal>"
      - "<zamanlayici> iptal"
    example: "zamanlayıcıyı iptal et"
    response: "default"
