---
# HassGetCurrentDate - default

language: "tr"
data:
  - sentences:
      - "bugün ayın kaçı"
      - "[bugünün] tarih[i] ne[dir]"
      - "tarihi söyle"
    example: "bugün ayın kaçı"
    response: "default"
