---
# HassTimerStatus - default

language: "tr"
data:
  - sentences:
      - "<zamanlayici_da> ne kadar (kaldı|var)"
      - "<zamanlayici> ne kadar (kaldı|var)"
      - "<zamanlayici> durumu [nedir]"
      - "kaç (dakika|saniye|saat) kaldı"
    example: "zamanlayıcıda ne kadar kaldı"
    response: "default"
