---
# HassSetVolume - default

language: "tr"
data:
  - sentences:
      - "<sesi> [yüzde] {volume:volume_level} yap"
      - "<sesi> %{volume:volume_level} yap"
    example: "sesi yüzde 50 yap"
    response: "default"
