---
# HassUnpauseTimer - default

language: "tr"
data:
  - sentences:
      - "<zamanlayici_i> <timer_devam>"
      - "<zamanlayici_ya> devam et"
    example: "zamanlayıcıyı devam ettir"
    response: "default"
