---
# HassMediaNext - default
# context_area: true

language: "tr"
data:
  - sentences:
      - "sonraki [<parca>]"
      - "sonrakine geç"
      - "[bu] <parcayi> (geç|atla)"
    example: "sonraki şarkı"
    response: "default"
