---
# HassMediaUnpause - default
# context_area: true

language: "tr"
data:
  - sentences:
      - "[<medyayi>] <medya_devam>"
      - "[<medyaya>] devam et"
    example: "müziği devam ettir"
    response: "default"
