---
# HassMediaPrevious - default

language: "tr"
data:
  - sentences:
      - "önceki [<parca>]"
      - "öncekine (geç|dön)"
      - "[bu] <parcayi> geri al"
    example: "önceki şarkı"
    response: "default"
