---
# HassPauseTimer - default

language: "tr"
data:
  - sentences:
      - "<zamanlayici_i> <timer_duraklat>"
      - "<zamanlayici_ya> ara ver"
    example: "zamanlayıcıyı duraklat"
    response: "default"
