---
# HassSetVolumeRelative - default

language: "tr"
data:
  - sentences:
      - "<sesi> {volume_step}"
      - "<sesi> [yüzde] {volume_step_up:volume_step} <ses_yukselt>"
      - "<sesi> [yüzde] {volume_step_down:volume_step} <ses_kis>"
    example: "sesi yükselt"
    response: "default"
